### ISSUE TITLE
Create a generalized notion of 'views'

### ISSUE THREAD

**Issue by smalls** [PolymerLabs/model-viewer#4]
It should be possible to create a new type of view (e.g., VR, off-screen rendering) as mixins.

Consider renaming 'views' to 'modes' - views is overloaded, and we already refer to these as modes in some of the docs.

Note that it may make sense to have tasks or new issues to create those mixins when we pick this work up.

**Comment by jsantell** [comment]
The mixins pattern implemented via #38 makes this issue either solved or redundant
